export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_LOGIN_USER = 'ADD_LOGIN_USER';
export const ADD_CURRENT_DATE = 'ADD_CURRENT_DATE';
export const CHANGE_ACTIVE_QUESTION = 'CHANGE_ACTIVE_QUESTION';
export const ADD_SOCKET = 'ADD_SOCKET';
export const DISABLED_TO_DEVICES = 'DISABLED_TO_DEVICES';